# Generated by Django 4.2.1 on 2023-07-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MFAMStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=255, unique=True)),
                ("exchange", models.CharField(max_length=255)),
                (
                    "acquirers_multiple",
                    models.DecimalField(decimal_places=3, max_digits=20, null=True),
                ),
                ("mf_rank", models.PositiveIntegerField(null=True)),
                ("am_rank", models.PositiveIntegerField(null=True)),
                ("mf_am_rank", models.PositiveIntegerField(null=True)),
            ],
            options={
                "ordering": ("mf_am_rank",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Active"), (2, "Inactive"), (3, "Archived")]
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
    ]
